### PR TITLE
Arrow

### PR DESCRIPTION
**Pull request by MohitBansal321**
#76

### CODE REVIEW

**Comment by MohitBansal321** [comment]
@s0 please now you check
i replace almost all binds with arrow functions

**Comment by s0** [comment]
You're number of commits for this pull request is very long, are you not pulling from the main `develop` branch before doing the work? If not, I suggest rebasing to clean up your history.

Try running:

```
git rebase origin/develop
git push -f
```

**Comment by MohitBansal321** [comment]
```
PS C:\Users\SUPER\Desktop\openSource\synesthesia> git remote -vv
origin  https://github.com/MohitBansal321/synesthesia.git (fetch)
origin  https://github.com/MohitBansal321/synesthesia.git (push)
upstream        https://github.com/synesthesia-project/synesthesia.git (fetch)
upstream        https://github.com/synesthesia-project/synesthesia.git (push) 
```
Now I have to do this?
git rebase origin/develop
git push -f

let me know

**Comment by s0** [comment]
Do the following:

```
git fetch upstream develop
git rebase upstream/develop
git push origin HEAD:arrow
```

**Comment by MohitBansal321** [comment]
```
PS C:\Users\SUPER\Desktop\openSource\synesthesia> git push origin HEAD:arrow
To https://github.com/MohitBansal321/synesthesia.git
 ! [rejected]        HEAD -> arrow (non-fast-forward)
error: failed to push some refs to 'https://github.com/MohitBansal321/synesthesia.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```
sorry to disturb you again but getting this error

**Comment by MohitBansal321** [comment]
```
git fetch upstream develop
git rebase upstream/develop
git push origin HEAD:arrow
```

**In which branch i should run this command arrow or develop branch**

**Comment by MohitBansal321** [comment]
sorry for this too many commit 
but i think now it is okay
all branches are up to date and there is no conflict between any branch

**Comment by MohitBansal321** [comment]
@s0 it's 2 week ago
kindly merge and close

**Review by s0 — APPROVED** [review]

**Pull request merged**
