### PR TITLE
done rush lint:fix + replace binds with arrow function

### PR DESCRIPTION
**Pull request by MohitBansal321**
#76 check it i changes two files
composer/src/scripts/ts/components/integration-button.tsx
composer/src/scripts/ts/components/item-properties.tsx

after changes i did rush lint:fix

### CODE REVIEW

**Comment by MohitBansal321** [comment]
If all things are good  🙂 then i will work on other parts too

**Review by s0 — APPROVED** [review]

**Comment by s0** [comment]
Cool approved!

For future reference, you don't need to close and open a new PR when you make changes, you can just push / force-push to your existing branch and the pull request will update :)

**Comment by s0** [comment]
that should be it, you didn't need to close and open a new PR as well, that should have been sufficient :)

**Comment by MohitBansal321** [comment]
after this i changed one file but didn't see any compare and pull request option

**Comment by s0** [comment]
That would be because your pull request was already open, so you didn't need to open a new one.

**Comment by s0** [comment]
Ah you pushed your first PR to the branch `develop` and your second one to `arrow`, that's why! =) You could just have kept using the same one

**Pull request merged**
