### PR TITLE
replace bind with arrow function

### PR DESCRIPTION
**Pull request by MohitBansal321**
Please ensure me it is correct so I start changing all binds with the arrow function

### CODE REVIEW

**Review by s0 — CHANGES_REQUESTED** [review]
Not quite, you need to change the definition of the function, and remove the call to `bind` (not replace the call to bind)

**Comment by MohitBansal321** [comment]
can you give an example of it so I understand it better

**Comment by s0** [comment]
This plugin's documentation has some good examples, and if you add it to the eslint config, it will probably help find them all: https://www.npmjs.com/package/eslint-plugin-prefer-arrow-functions

**Comment by s0** [comment]
I have a feeling that the formatting is incorrect. Also the pull request checks aren't working for forks at the moment, will look into that.

For formatting, please run `rush lint:fix`

**Comment by MohitBansal321** [comment]
> I have a feeling that the formatting is incorrect. Also the pull request checks aren't working for forks at the moment, will look into that.
> 
> For formatting, please run `rush lint:fix`

This rush lint: fix  command  is not working with node js version 16
I also used gulp lint: fix it throws the error: invalid option :tslintSrc

**Comment by MohitBansal321** [comment]
I formatted too in balccon/src/index.ts
let me know is it okay

**Comment by s0** [comment]
> This rush lint: fix command is not working with node js version 16

How are you trying to run it, have you installed rush already? It needs to be installed separately, or run with `npx`. It works with Node 16 as you can see here in the CI: https://github.com/synesthesia-project/synesthesia/actions/runs/3952560941/jobs/6767791056

```
npx @microsoft/rush update && npx @microsoft/rush lint
```

**Comment by MohitBansal321** [comment]
> > This rush lint: fix command is not working with node js version 16
> 
> How are you trying to run it, have you installed rush already? It needs to be installed separately, or run with `npx`. It works with Node 16 as you can see here in the CI: https://github.com/synesthesia-project/synesthesia/actions/runs/3952560941/jobs/6767791056
> 
> ```
> npx @microsoft/rush update && npx @microsoft/rush lint:fix
> ```
> 
> or
> 
> ```
> npm install -g @microsoft/rush
> rush update
> rush lint:fix
> ```

okay i will check what happen

**Comment by MohitBansal321** [comment]
error

sir same error
@s0

**Comment by MohitBansal321** [comment]
i will open new fresh pull request for it

**Pull request closed without merging**
